name: Deploy to Firebase Hosting

on:
  push:
    branches: ["**"]           # 全ブランチ
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: hosting-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (app)
        working-directory: app
        run: npm ci

      - name: Build (app)
        working-directory: app
        run: npm run build

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@latest

      # サービスアカウントで認証（Secrets に JSON 文字列を入れてある前提）
      - name: Write service account key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/sa.json" >> $GITHUB_ENV

      - name: Show firebase.json for sanity
        run: |
          echo "Workspace:"
          pwd
          ls -la
          echo "firebase.json:"
          cat firebase.json

      # --- 本番デプロイ（main の push） ---
      - name: Deploy LIVE (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          firebase --version
          # firebase.json の hosting.public が app/dist になっていることを想定
          firebase deploy --project kayak-gogo --only "hosting" --non-interactive --message "$GITHUB_SHA"

      # --- プレビュー（PR / 非 main ブランチ） ---
      - name: Deploy PREVIEW (PR / non-main)
        if: |
          github.event_name == 'pull_request' ||
          (github.event_name == 'push' && github.ref != 'refs/heads/main')
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          firebase --version
          # チャンネル名は PR番号 or ブランチ名
          CHANNEL="${{ github.event.pull_request.number || github.ref_name }}"
          firebase hosting:channel:deploy "$CHANNEL" \
            --project kayak-gogo \
            --expires 7d \
            --non-interactive

      # --- （任意）PR にプレビューURLコメントを送る ---
      - name: Comment preview URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require('node:child_process');
            const channel = context.payload.pull_request.number.toString();
            const out = execSync(`firebase hosting:channel:list --project kayak-gogo --json`, { encoding: 'utf8' });
            const data = JSON.parse(out);
            const item = data.result.find(x => x.name.endsWith(`/channels/${channel}`));
            if (item && item.url) {
              const body = `✅ Preview deployed: ${item.url}`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body
              });
            }
